// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.12.4
// source: gateway/gatewaypb/gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StringMessage) Reset() {
	*x = StringMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gatewaypb_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMessage) ProtoMessage() {}

func (x *StringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gatewaypb_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMessage.ProtoReflect.Descriptor instead.
func (*StringMessage) Descriptor() ([]byte, []int) {
	return file_gateway_gatewaypb_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *StringMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_gateway_gatewaypb_gateway_proto protoreflect.FileDescriptor

var file_gateway_gatewaypb_gateway_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0x21, 0x0a, 0x0d, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x47, 0x0a,
	0x0b, 0x44, 0x65, 0x6d, 0x6f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x38, 0x0a, 0x04,
	0x45, 0x63, 0x68, 0x6f, 0x12, 0x16, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x16, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_gatewaypb_gateway_proto_rawDescOnce sync.Once
	file_gateway_gatewaypb_gateway_proto_rawDescData = file_gateway_gatewaypb_gateway_proto_rawDesc
)

func file_gateway_gatewaypb_gateway_proto_rawDescGZIP() []byte {
	file_gateway_gatewaypb_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_gatewaypb_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_gatewaypb_gateway_proto_rawDescData)
	})
	return file_gateway_gatewaypb_gateway_proto_rawDescData
}

var file_gateway_gatewaypb_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_gatewaypb_gateway_proto_goTypes = []interface{}{
	(*StringMessage)(nil), // 0: gateway.StringMessage
}
var file_gateway_gatewaypb_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.DemoGateway.Echo:input_type -> gateway.StringMessage
	0, // 1: gateway.DemoGateway.Echo:output_type -> gateway.StringMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_gatewaypb_gateway_proto_init() }
func file_gateway_gatewaypb_gateway_proto_init() {
	if File_gateway_gatewaypb_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_gatewaypb_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_gatewaypb_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_gatewaypb_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_gatewaypb_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_gatewaypb_gateway_proto_msgTypes,
	}.Build()
	File_gateway_gatewaypb_gateway_proto = out.File
	file_gateway_gatewaypb_gateway_proto_rawDesc = nil
	file_gateway_gatewaypb_gateway_proto_goTypes = nil
	file_gateway_gatewaypb_gateway_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DemoGatewayClient is the client API for DemoGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoGatewayClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
}

type demoGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoGatewayClient(cc grpc.ClientConnInterface) DemoGatewayClient {
	return &demoGatewayClient{cc}
}

func (c *demoGatewayClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/gateway.DemoGateway/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoGatewayServer is the server API for DemoGateway service.
type DemoGatewayServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
}

// UnimplementedDemoGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedDemoGatewayServer struct {
}

func (*UnimplementedDemoGatewayServer) Echo(context.Context, *StringMessage) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}

func RegisterDemoGatewayServer(s *grpc.Server, srv DemoGatewayServer) {
	s.RegisterService(&_DemoGateway_serviceDesc, srv)
}

func _DemoGateway_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoGatewayServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.DemoGateway/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoGatewayServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemoGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.DemoGateway",
	HandlerType: (*DemoGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _DemoGateway_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/gatewaypb/gateway.proto",
}
