// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: gateway/gatewaypb/gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DemoGatewayClient is the client API for DemoGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoGatewayClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
}

type demoGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoGatewayClient(cc grpc.ClientConnInterface) DemoGatewayClient {
	return &demoGatewayClient{cc}
}

func (c *demoGatewayClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/gateway.DemoGateway/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoGatewayServer is the server API for DemoGateway service.
// All implementations must embed UnimplementedDemoGatewayServer
// for forward compatibility
type DemoGatewayServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
	mustEmbedUnimplementedDemoGatewayServer()
}

// UnimplementedDemoGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedDemoGatewayServer struct {
}

func (UnimplementedDemoGatewayServer) Echo(context.Context, *StringMessage) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedDemoGatewayServer) mustEmbedUnimplementedDemoGatewayServer() {}

// UnsafeDemoGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoGatewayServer will
// result in compilation errors.
type UnsafeDemoGatewayServer interface {
	mustEmbedUnimplementedDemoGatewayServer()
}

func RegisterDemoGatewayServer(s grpc.ServiceRegistrar, srv DemoGatewayServer) {
	s.RegisterService(&DemoGateway_ServiceDesc, srv)
}

func _DemoGateway_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoGatewayServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gateway.DemoGateway/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoGatewayServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// DemoGateway_ServiceDesc is the grpc.ServiceDesc for DemoGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.DemoGateway",
	HandlerType: (*DemoGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _DemoGateway_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/gatewaypb/gateway.proto",
}
